### ISSUE TITLE
Uncaught ReferenceError: require is not defined

### ISSUE THREAD

**Issue by ApolloTang** [voronianski/babel-transform-in-browser#2]
I can't get the example to work, do I need require.js?

at line 4:
var _getPrototypeOf = require('babel-runtime/core-js/object/get-prototype-of');

**Comment by voronianski** [comment]
@ApolloTang nope, sorry, it's my fault, fixed in `6.4.6` already.

**Comment by ApolloTang** [comment]
Thanks, working now :)
